# Generated by Django 5.2.4 on 2025-08-12 11:33

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_code", models.CharField(blank=True, max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9+\\-\\s]{8,20}$", "Invalid phone number"
                            )
                        ],
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="hr/profile/"),
                ),
                ("aadhaar_last4", models.CharField(blank=True, max_length=4)),
                (
                    "aadhaar_doc_front",
                    models.FileField(
                        blank=True, null=True, upload_to="hr/docs/aadhaar/"
                    ),
                ),
                (
                    "aadhaar_doc_back",
                    models.FileField(
                        blank=True, null=True, upload_to="hr/docs/aadhaar/"
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{5}[0-9]{4}[A-Z]$", "PAN must match AAAAA9999A"
                            )
                        ],
                    ),
                ),
                (
                    "pan_doc",
                    models.FileField(blank=True, null=True, upload_to="hr/docs/pan/"),
                ),
                ("department", models.CharField(blank=True, max_length=120)),
                ("designation", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("INACTIVE", "Inactive"),
                            ("EXITED", "Exited"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("date_of_joining", models.DateField()),
                (
                    "salary_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("salary_currency", models.CharField(default="INR", max_length=3)),
                (
                    "salary_period",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("ANNUAL", "Annual")],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.accessprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("AADHAAR", "Aadhaar"),
                            ("PAN", "PAN"),
                            ("OFFER", "Offer Letter"),
                            ("APPOINT", "Appointment Letter"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=50)),
                ("file", models.FileField(upload_to="hr/docs/other/")),
                ("issued_on", models.DateField(blank=True, null=True)),
                ("valid_till", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalAccessProfile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical access profile",
                "verbose_name_plural": "historical access profiles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmployee",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "emp_code",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9+\\-\\s]{8,20}$", "Invalid phone number"
                            )
                        ],
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "profile_image",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("aadhaar_last4", models.CharField(blank=True, max_length=4)),
                (
                    "aadhaar_doc_front",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                (
                    "aadhaar_doc_back",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{5}[0-9]{4}[A-Z]$", "PAN must match AAAAA9999A"
                            )
                        ],
                    ),
                ),
                ("pan_doc", models.TextField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("designation", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("INACTIVE", "Inactive"),
                            ("EXITED", "Exited"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("date_of_joining", models.DateField()),
                (
                    "salary_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("salary_currency", models.CharField(default="INR", max_length=3)),
                (
                    "salary_period",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("ANNUAL", "Annual")],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "access_profile",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.accessprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical employee",
                "verbose_name_plural": "historical employees",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("AADHAAR", "Aadhaar"),
                            ("PAN", "PAN"),
                            ("OFFER", "Offer Letter"),
                            ("APPOINT", "Appointment Letter"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=50)),
                ("file", models.TextField(max_length=100)),
                ("issued_on", models.DateField(blank=True, null=True)),
                ("valid_till", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical employee document",
                "verbose_name_plural": "historical employee documents",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                django.db.models.functions.text.Lower("first_name"),
                name="idx_emp_first_name_lower",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["emp_code"], name="hr_employee_emp_cod_7e3fc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["status", "department", "designation", "date_of_joining"],
                name="hr_employee_status_263478_idx",
            ),
        ),
    ]
