# Generated by Django 5.2.4 on 2025-08-14 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        # Remove all HR models and their tables
        migrations.DeleteModel(name='HRFieldChange'),
        migrations.DeleteModel(name='EmployeeDocument'),
        migrations.DeleteModel(name='Employee'),
        migrations.DeleteModel(name='AccessProfile'),
        migrations.DeleteModel(name='Position'),
        migrations.DeleteModel(name='OrgUnit'),
        
        # Remove historical tables created by django-simple-history
        migrations.RunSQL(
            "DROP TABLE IF EXISTS hr_historicalemployee CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS hr_historicalemployeedocument CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS hr_historicalaccessprofile CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS hr_historicalposition CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS hr_historicalorgunit CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
