# Generated by Django 5.2.4 on 2025-08-13 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0006_copy_fk_data_to_main_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="department_fk",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="designation_fk",
        ),
        migrations.RemoveField(
            model_name="historicalemployee",
            name="department_fk",
        ),
        migrations.RemoveField(
            model_name="historicalemployee",
            name="designation_fk",
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.designation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalemployee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="hr.department",
            ),
        ),
        migrations.AlterField(
            model_name="historicalemployee",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="hr.designation",
            ),
        ),
    ]
