# Generated by Django 5.2.4 on 2025-08-12 13:22

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CvHubState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CvHubEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_name", models.CharField(max_length=200)),
                ("trade_name", models.CharField(blank=True, max_length=200)),
                (
                    "constitution",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("PROPRIETORSHIP", "Proprietorship"),
                            ("PARTNERSHIP", "Partnership"),
                            ("PVTLTD", "Private Limited"),
                            ("LLP", "LLP"),
                            ("TRUST", "Trust"),
                            ("GOVT", "Government"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("BLACKLISTED", "Blacklisted"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("is_customer", models.BooleanField(default=False)),
                ("is_supplier", models.BooleanField(default=False)),
                ("is_vendor", models.BooleanField(default=False)),
                ("is_logistics", models.BooleanField(default=False)),
                ("for_sales", models.BooleanField(default=False)),
                ("for_purchase", models.BooleanField(default=False)),
                ("website", models.URLField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cv_hub_entry_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cv_hub_entry_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CvHubContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("designation", models.CharField(blank=True, max_length=120)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9+\\-\\s]{8,20}$", "Invalid phone"
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="cv_hub.cvhubentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CvHubGSTRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taxpayer_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("COMPOSITION", "Composition"),
                            ("CASUAL", "Casual"),
                            ("UNREGISTERED", "Unregistered"),
                            ("OTHER", "Other"),
                        ],
                        default="UNREGISTERED",
                        max_length=20,
                    ),
                ),
                ("gstin", models.CharField(blank=True, max_length=15, null=True)),
                ("legal_name_of_business", models.CharField(max_length=200)),
                ("trade_name", models.CharField(blank=True, max_length=200)),
                (
                    "effective_date_of_registration",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "constitution_of_business",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("PROPRIETORSHIP", "Proprietorship"),
                            ("PARTNERSHIP", "Partnership"),
                            ("PVTLTD", "Private Limited"),
                            ("LLP", "LLP"),
                            ("TRUST", "Trust"),
                            ("GOVT", "Government"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "gstin_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CANCELLED", "Cancelled"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("principal_place_of_business", models.TextField(blank=True)),
                ("business_activities", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CANCELLED", "Cancelled"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="cv_hub.cvhubentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CvHubCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="cv_hub.cvhubstate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CvHubAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered Office"),
                            ("BILLING", "Billing"),
                            ("SHIPPING", "Shipping"),
                            ("PLANT", "Plant/Factory"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("line1", models.CharField(max_length=200)),
                ("line2", models.CharField(blank=True, max_length=200)),
                ("pincode", models.CharField(max_length=10)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_default_billing", models.BooleanField(default=False)),
                ("is_default_shipping", models.BooleanField(default=False)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cv_hub.cvhubcity",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="cv_hub.cvhubentry",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cv_hub.cvhubstate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalCvHubAddress",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered Office"),
                            ("BILLING", "Billing"),
                            ("SHIPPING", "Shipping"),
                            ("PLANT", "Plant/Factory"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("line1", models.CharField(max_length=200)),
                ("line2", models.CharField(blank=True, max_length=200)),
                ("pincode", models.CharField(max_length=10)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_default_billing", models.BooleanField(default=False)),
                ("is_default_shipping", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cv_hub.cvhubcity",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cv_hub.cvhubentry",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cv_hub.cvhubstate",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cv hub address",
                "verbose_name_plural": "historical cv hub addresss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCvHubContact",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("designation", models.CharField(blank=True, max_length=120)),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9+\\-\\s]{8,20}$", "Invalid phone"
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_primary", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cv_hub.cvhubentry",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cv hub contact",
                "verbose_name_plural": "historical cv hub contacts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCvHubEntry",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("legal_name", models.CharField(max_length=200)),
                ("trade_name", models.CharField(blank=True, max_length=200)),
                (
                    "constitution",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("PROPRIETORSHIP", "Proprietorship"),
                            ("PARTNERSHIP", "Partnership"),
                            ("PVTLTD", "Private Limited"),
                            ("LLP", "LLP"),
                            ("TRUST", "Trust"),
                            ("GOVT", "Government"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("BLACKLISTED", "Blacklisted"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("is_customer", models.BooleanField(default=False)),
                ("is_supplier", models.BooleanField(default=False)),
                ("is_vendor", models.BooleanField(default=False)),
                ("is_logistics", models.BooleanField(default=False)),
                ("for_sales", models.BooleanField(default=False)),
                ("for_purchase", models.BooleanField(default=False)),
                ("website", models.URLField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cv hub entry",
                "verbose_name_plural": "historical cv hub entrys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCvHubGSTRegistration",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "taxpayer_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("COMPOSITION", "Composition"),
                            ("CASUAL", "Casual"),
                            ("UNREGISTERED", "Unregistered"),
                            ("OTHER", "Other"),
                        ],
                        default="UNREGISTERED",
                        max_length=20,
                    ),
                ),
                ("gstin", models.CharField(blank=True, max_length=15, null=True)),
                ("legal_name_of_business", models.CharField(max_length=200)),
                ("trade_name", models.CharField(blank=True, max_length=200)),
                (
                    "effective_date_of_registration",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "constitution_of_business",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("PROPRIETORSHIP", "Proprietorship"),
                            ("PARTNERSHIP", "Partnership"),
                            ("PVTLTD", "Private Limited"),
                            ("LLP", "LLP"),
                            ("TRUST", "Trust"),
                            ("GOVT", "Government"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "gstin_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CANCELLED", "Cancelled"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("principal_place_of_business", models.TextField(blank=True)),
                ("business_activities", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CANCELLED", "Cancelled"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cv_hub.cvhubentry",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cv hub gst registration",
                "verbose_name_plural": "historical cv hub gst registrations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="cvhubentry",
            index=models.Index(
                fields=["status", "constitution"], name="cv_hub_cvhu_status_c4e1ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cvhubentry",
            index=models.Index(
                fields=["for_sales", "for_purchase"],
                name="cv_hub_cvhu_for_sal_5e9b78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cvhubgstregistration",
            index=models.Index(fields=["gstin"], name="cv_hub_cvhu_gstin_0451ad_idx"),
        ),
        migrations.AddIndex(
            model_name="cvhubgstregistration",
            index=models.Index(
                fields=["taxpayer_type", "gstin_status"],
                name="cv_hub_cvhu_taxpaye_e6bfce_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cvhubcity",
            unique_together={("state", "name")},
        ),
        migrations.AddIndex(
            model_name="cvhubaddress",
            index=models.Index(
                fields=["state", "city"], name="cv_hub_cvhu_state_i_d15b2a_idx"
            ),
        ),
    ]
