# Generated by Django 5.2.4 on 2025-08-12 16:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cv_hub", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cvhubcontact",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cv_hub_contact_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cvhubcontact",
            name="first_name",
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name="cvhubcontact",
            name="last_name",
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name="cvhubcontact",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cv_hub_contact_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cvhubgstregistration",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cv_hub_gst_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cvhubgstregistration",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cv_hub_gst_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcvhubcontact",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcvhubcontact",
            name="first_name",
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name="historicalcvhubcontact",
            name="last_name",
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name="historicalcvhubcontact",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcvhubgstregistration",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcvhubgstregistration",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cvhubcontact",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CEO", "Chief Executive Officer"),
                    ("CFO", "Chief Financial Officer"),
                    ("CTO", "Chief Technology Officer"),
                    ("MANAGER", "Manager"),
                    ("ASSISTANT_MANAGER", "Assistant Manager"),
                    ("EXECUTIVE", "Executive"),
                    ("SENIOR_EXECUTIVE", "Senior Executive"),
                    ("ACCOUNTANT", "Accountant"),
                    ("SALES_MANAGER", "Sales Manager"),
                    ("PURCHASE_MANAGER", "Purchase Manager"),
                    ("DIRECTOR", "Director"),
                    ("PARTNER", "Partner"),
                    ("PROPRIETOR", "Proprietor"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cvhubcontact",
            name="phone",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9+\\-\\s]{8,10}$", "Phone number must be 8-10 digits"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcvhubcontact",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CEO", "Chief Executive Officer"),
                    ("CFO", "Chief Financial Officer"),
                    ("CTO", "Chief Technology Officer"),
                    ("MANAGER", "Manager"),
                    ("ASSISTANT_MANAGER", "Assistant Manager"),
                    ("EXECUTIVE", "Executive"),
                    ("SENIOR_EXECUTIVE", "Senior Executive"),
                    ("ACCOUNTANT", "Accountant"),
                    ("SALES_MANAGER", "Sales Manager"),
                    ("PURCHASE_MANAGER", "Purchase Manager"),
                    ("DIRECTOR", "Director"),
                    ("PARTNER", "Partner"),
                    ("PROPRIETOR", "Proprietor"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcvhubcontact",
            name="phone",
            field=models.CharField(
                db_index=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9+\\-\\s]{8,10}$", "Phone number must be 8-10 digits"
                    )
                ],
            ),
        ),
    ]
