# Generated by Django 5.2.4 on 2025-08-12 16:34

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cv_hub", "0002_cvhubcontact_created_by_cvhubcontact_first_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvhubcontact",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9+\\-\\s]{8,10}$", "Phone number must be 8-10 digits"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cvhubgstregistration",
            name="gstin",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalcvhubcontact",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9+\\-\\s]{8,10}$", "Phone number must be 8-10 digits"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcvhubgstregistration",
            name="gstin",
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AddConstraint(
            model_name="cvhubcontact",
            constraint=models.UniqueConstraint(
                fields=("entry", "phone"), name="unique_phone_per_entry"
            ),
        ),
        migrations.AddConstraint(
            model_name="cvhubgstregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("gstin__isnull", False), models.Q(("gstin", ""), _negated=True)
                ),
                fields=("gstin",),
                name="unique_gstin_when_not_null",
            ),
        ),
    ]
