# Generated by Django 5.2.4 on 2025-08-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cv_hub", "0003_alter_cvhubcontact_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvhubgstregistration",
            name="gstin",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcvhubgstregistration",
            name="gstin",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
