# Generated by Django 5.2.4 on 2025-08-12 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cv_hub", "0004_alter_cvhubgstregistration_gstin_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cvhubgstregistration",
            name="unique_gstin_when_not_null",
        ),
    ]
