# Generated by Django 5.2.4 on 2025-08-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_pricecoverage_guard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelisttier",
            name="max_qty",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Applies up to and including this quantity; leave empty if open-ended",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelisttier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_open_ended", True)),
                fields=("price_list_item", "is_open_ended"),
                name="uniq_open_ended_per_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelisttier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_open_ended", True), ("max_qty__isnull", True)),
                    models.Q(("is_open_ended", False), ("max_qty__isnull", False)),
                    _connector="OR",
                ),
                name="ck_openended_requires_null_maxqty",
            ),
        ),
    ]
