# Generated by Django 5.2.4 on 2025-08-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0002_historicalterritory_territory_territorymember_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerritoryCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pincode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="geo.pincode"
                    ),
                ),
                (
                    "territory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage",
                        to="geo.territory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Territory Coverage",
                "verbose_name_plural": "Territory Coverage",
                "indexes": [
                    models.Index(
                        fields=["territory"], name="geo_territo_territo_731613_idx"
                    ),
                    models.Index(
                        fields=["pincode"], name="geo_territo_pincode_10f7e7_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("territory", "pincode"),
                        name="uniq_territory_pincode_coverage",
                    )
                ],
            },
        ),
    ]
