# Generated by Django 5.2.4 on 2025-08-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_vendor_hub", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("partner",),
                name="uniq_primary_address_per_partner",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("partner",),
                name="uniq_primary_contact_per_partner",
            ),
        ),
        migrations.AddConstraint(
            model_name="gstregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("partner",),
                name="uniq_default_gst_per_partner",
            ),
        ),
    ]
