# Generated by Django 5.2.4 on 2025-08-09 17:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalWarehouse",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "warehouse_id",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, null=True
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32)),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("gstin", models.CharField(max_length=15)),
                ("address_line1", models.CharField(blank=True, max_length=180)),
                ("address_line2", models.CharField(blank=True, max_length=180)),
                ("city", models.CharField(max_length=80)),
                ("state", models.CharField(max_length=80)),
                ("pincode", models.CharField(max_length=12)),
                ("country", models.CharField(default="India", max_length=80)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Warehouse",
                "verbose_name_plural": "historical Warehouses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warehouse_id",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, null=True, unique=True
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("gstin", models.CharField(max_length=15)),
                ("address_line1", models.CharField(blank=True, max_length=180)),
                ("address_line2", models.CharField(blank=True, max_length=180)),
                ("city", models.CharField(max_length=80)),
                ("state", models.CharField(max_length=80)),
                ("pincode", models.CharField(max_length=12)),
                ("country", models.CharField(default="India", max_length=80)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PHYSICAL", "PHYSICAL"), ("VIRTUAL", "VIRTUAL")],
                        max_length=8,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RECEIVE", "RECEIVE"),
                            ("DISPATCH", "DISPATCH"),
                            ("RETURN", "RETURN"),
                            ("QC", "QC"),
                            ("HOLD", "HOLD"),
                            ("DAMAGE", "DAMAGE"),
                            ("LOST", "LOST"),
                            ("EXCESS", "EXCESS"),
                            ("LOST_PENDING", "LOST_PENDING"),
                            ("EXCESS_PENDING", "EXCESS_PENDING"),
                            ("DAMAGE_PENDING", "DAMAGE_PENDING"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("code", models.CharField(blank=True, max_length=32)),
                ("system_managed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="warehousing.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="HistoricalLocation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PHYSICAL", "PHYSICAL"), ("VIRTUAL", "VIRTUAL")],
                        max_length=8,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RECEIVE", "RECEIVE"),
                            ("DISPATCH", "DISPATCH"),
                            ("RETURN", "RETURN"),
                            ("QC", "QC"),
                            ("HOLD", "HOLD"),
                            ("DAMAGE", "DAMAGE"),
                            ("LOST", "LOST"),
                            ("EXCESS", "EXCESS"),
                            ("LOST_PENDING", "LOST_PENDING"),
                            ("EXCESS_PENDING", "EXCESS_PENDING"),
                            ("DAMAGE_PENDING", "DAMAGE_PENDING"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("code", models.CharField(blank=True, max_length=32)),
                ("system_managed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="warehousing.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Location",
                "verbose_name_plural": "historical Locations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["code"], name="warehousing_code_aff682_idx"),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["status"], name="warehousing_status_113a69_idx"),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["city"], name="warehousing_city_b20576_idx"),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["state"], name="warehousing_state_c3e76b_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["warehouse"], name="warehousing_warehou_ae57d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["status"], name="warehousing_status_46b534_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["type"], name="warehousing_type_9e867e_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["subtype"], name="warehousing_subtype_fc8f4c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "PHYSICAL")),
                fields=("warehouse", "code"),
                name="uq_location_code_per_wh",
            ),
        ),
    ]
