# Generated by Django 5.0.4 on 2025-08-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehousing", "0003_physical_storage_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallocation",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STORAGE", "STORAGE"),
                    ("RECEIVE", "RECEIVE"),
                    ("DISPATCH", "DISPATCH"),
                    ("RETURN", "RETURN"),
                    ("QC", "QC"),
                    ("HOLD", "HOLD"),
                    ("DAMAGE", "DAMAGE"),
                    ("LOST", "LOST"),
                    ("EXCESS", "EXCESS"),
                    ("LOST_PENDING", "LOST_PENDING"),
                    ("EXCESS_PENDING", "EXCESS_PENDING"),
                    ("DAMAGE_PENDING", "DAMAGE_PENDING"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
