# Generated by Django 5.0.4 on 2025-08-11 08:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_historicalitem_item"),
        ("warehousing", "0004_alter_historicallocation_subtype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAdjustmentRequest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "number",
                    models.CharField(db_index=True, editable=False, max_length=20),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DAMAGE", "DAMAGE"),
                            ("LOST", "LOST"),
                            ("EXCESS", "EXCESS"),
                        ],
                        max_length=10,
                    ),
                ),
                ("qty", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "REQUESTED"),
                            ("APPROVED", "APPROVED"),
                            ("DECLINED", "DECLINED"),
                        ],
                        default="REQUESTED",
                        max_length=10,
                    ),
                ),
                ("memo", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(blank=True, editable=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "declined_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.item",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="warehousing.location",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="warehousing.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical adjustment request",
                "verbose_name_plural": "historical adjustment requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStockLedger",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("ts", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("qty_delta", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("ADJ_REQ_DAMAGE", "Adj Req Damage"),
                            ("ADJ_REQ_LOST", "Adj Req Lost"),
                            ("ADJ_REQ_EXCESS", "Adj Req Excess"),
                            ("ADJ_APPROVE_DAMAGE", "Adj Approve Damage"),
                            ("ADJ_DECLINE_DAMAGE", "Adj Decline Damage"),
                            ("ADJ_APPROVE_LOST", "Adj Approve Lost"),
                            ("ADJ_DECLINE_LOST", "Adj Decline Lost"),
                            ("ADJ_APPROVE_EXCESS", "Adj Approve Excess"),
                            ("TRANSFER", "Transfer"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ref_model", models.CharField(blank=True, max_length=50)),
                ("ref_id", models.CharField(blank=True, max_length=50)),
                ("memo", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="warehousing.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="warehousing.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Stock Ledger Entry",
                "verbose_name_plural": "historical Stock Ledger",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AdjustmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DAMAGE", "DAMAGE"),
                            ("LOST", "LOST"),
                            ("EXCESS", "EXCESS"),
                        ],
                        max_length=10,
                    ),
                ),
                ("qty", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "REQUESTED"),
                            ("APPROVED", "APPROVED"),
                            ("DECLINED", "DECLINED"),
                        ],
                        default="REQUESTED",
                        max_length=10,
                    ),
                ),
                ("memo", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adj_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "declined_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adj_declined",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.item",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adj_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="warehousing.location",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustment_requests",
                        to="warehousing.warehouse",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["warehouse", "status"],
                        name="warehousing_warehou_707116_idx",
                    ),
                    models.Index(
                        fields=["requested_at"], name="warehousing_request_5536e0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("qty_delta", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("ADJ_REQ_DAMAGE", "Adj Req Damage"),
                            ("ADJ_REQ_LOST", "Adj Req Lost"),
                            ("ADJ_REQ_EXCESS", "Adj Req Excess"),
                            ("ADJ_APPROVE_DAMAGE", "Adj Approve Damage"),
                            ("ADJ_DECLINE_DAMAGE", "Adj Decline Damage"),
                            ("ADJ_APPROVE_LOST", "Adj Approve Lost"),
                            ("ADJ_DECLINE_LOST", "Adj Decline Lost"),
                            ("ADJ_APPROVE_EXCESS", "Adj Approve Excess"),
                            ("TRANSFER", "Transfer"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ref_model", models.CharField(blank=True, max_length=50)),
                ("ref_id", models.CharField(blank=True, max_length=50)),
                ("memo", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="warehousing.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="warehousing.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Ledger Entry",
                "verbose_name_plural": "Stock Ledger",
                "indexes": [
                    models.Index(
                        fields=["warehouse", "item"],
                        name="warehousing_warehou_b613ca_idx",
                    ),
                    models.Index(
                        fields=["warehouse", "location"],
                        name="warehousing_warehou_cd9143_idx",
                    ),
                    models.Index(
                        fields=["movement_type", "ts"],
                        name="warehousing_movemen_deb645_idx",
                    ),
                ],
            },
        ),
    ]
