# Generated by Django 5.2.4 on 2025-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehousing", "0006_alter_historicalstockledger_movement_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstockledger",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("ADJ_REQ_DAMAGE", "Adj Req Damage"),
                    ("ADJ_REQ_LOST", "Adj Req Lost"),
                    ("ADJ_REQ_EXCESS", "Adj Req Excess"),
                    ("ADJ_APPROVE_DAMAGE", "Adj Approve Damage"),
                    ("ADJ_DECLINE_DAMAGE", "Adj Decline Damage"),
                    ("ADJ_APPROVE_LOST", "Adj Approve Lost"),
                    ("ADJ_DECLINE_LOST", "Adj Decline Lost"),
                    ("ADJ_APPROVE_EXCESS", "Adj Approve Excess"),
                    ("ADJ_DECLINE_EXCESS", "Adj Decline Excess"),
                    ("PUTAWAY", "Putaway"),
                    ("PUTAWAY_LOST", "Putaway Lost"),
                    ("TRANSFER", "Transfer"),
                    ("ADJ_DELETE_REQUEST", "Adj Delete Request"),
                    ("INTERNAL_TRANSFER", "Internal Transfer"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("ADJ_REQ_DAMAGE", "Adj Req Damage"),
                    ("ADJ_REQ_LOST", "Adj Req Lost"),
                    ("ADJ_REQ_EXCESS", "Adj Req Excess"),
                    ("ADJ_APPROVE_DAMAGE", "Adj Approve Damage"),
                    ("ADJ_DECLINE_DAMAGE", "Adj Decline Damage"),
                    ("ADJ_APPROVE_LOST", "Adj Approve Lost"),
                    ("ADJ_DECLINE_LOST", "Adj Decline Lost"),
                    ("ADJ_APPROVE_EXCESS", "Adj Approve Excess"),
                    ("ADJ_DECLINE_EXCESS", "Adj Decline Excess"),
                    ("PUTAWAY", "Putaway"),
                    ("PUTAWAY_LOST", "Putaway Lost"),
                    ("TRANSFER", "Transfer"),
                    ("ADJ_DELETE_REQUEST", "Adj Delete Request"),
                    ("INTERNAL_TRANSFER", "Internal Transfer"),
                ],
                max_length=32,
            ),
        ),
    ]
