# Generated by ChatGPT
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    dependencies = [
        ('warehousing', '0007_alter_historicalstockledger_movement_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PutawayBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=50)),
                ('fingerprint', models.TextField(help_text='Canonical JSON of merged actions used to compute digest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_batches_created', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='putaway_batches', to='warehousing.warehouse')),
            ],
            options={
                'verbose_name': 'Putaway Batch',
                'verbose_name_plural': 'Putaway Batches',
            },
        ),
        migrations.AddConstraint(
            model_name='putawaybatch',
            constraint=models.UniqueConstraint(fields=('warehouse', 'ref_id'), name='uq_putaway_batch_ref_per_wh'),
        ),
        migrations.AddIndex(
            model_name='putawaybatch',
            index=models.Index(fields=['warehouse', 'ref_id'], name='warehousin_putaway_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='putawaybatch',
            index=models.Index(fields=['created_at'], name='warehousin_putaway_created_idx'),
        ),
    ]
