# Generated by Django 5.2.4 on 2025-08-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehousing", "0008_putawaybatch"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="putawaybatch",
            new_name="warehousing_warehou_b20b70_idx",
            old_name="warehousin_putaway_ref_idx",
        ),
        migrations.RenameIndex(
            model_name="putawaybatch",
            new_name="warehousing_created_be4356_idx",
            old_name="warehousin_putaway_created_idx",
        ),
        migrations.AlterField(
            model_name="putawaybatch",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
