# Generated by Django 5.2.4 on 2025-08-14 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehousing",
            "0009_rename_warehousin_putaway_ref_idx_warehousing_warehou_b20b70_idx_and_more",
        ),
    ]

    operations = []
